name: octoloupe
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  flutter_map_cancellable_tile_provider: ^3.0.2
  url_launcher: ^6.0.20
  http: ^1.2.2
  mailer: ^6.2.0
  flutter_dotenv: ^5.2.1
  persistent_bottom_nav_bar: ^6.2.1
  flutter_local_notifications: ^17.2.4
  image_picker: ^1.1.2

  cupertino_icons: ^1.0.8
  google_maps_flutter: ^2.9.0
  mongo_dart: ^0.10.3
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  flutter_spinkit: ^5.2.1
  firebase_storage: ^12.3.6
  firebase_analytics: ^11.3.6
  firebase_performance: ^0.10.0+11
  google_fonts: ^6.2.1
  flutter_launcher_icons: ^0.14.3
  firebase_crashlytics: ^4.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon_app.webp"
  remove_alpha_ios: true

  
flutter:
  uses-material-design: true
  assets:
    - assets/fonts/GreatVibes-Regular.ttf
    - assets/fonts/Poppins-Regular.ttf
    - assets/fonts/Satisfy-Regular.ttf
    - assets/images/Octoloupe.webp
    - assets/images/
    - assets/icons/
  fonts:
    - family: 'GreatVibes'
      fonts:
        - asset: assets/fonts/GreatVibes-Regular.ttf

    - family: 'Poppins-Regular'
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf

    - family: 'Satisfy-Regular'
      fonts:
        - asset: assets/fonts/Satisfy-Regular.ttf