// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1Ku2LIlLT2q5nSt9-49vfPHEV5GraoEo',
    appId: '1:655391099057:web:62c1bdbcd69b98f5f73a90',
    messagingSenderId: '655391099057',
    projectId: 'octoloupe-c814f',
    authDomain: 'octoloupe-c814f.firebaseapp.com',
    storageBucket: 'octoloupe-c814f.firebasestorage.app',
    measurementId: 'G-9YX7L2V4ZG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgZRAPkpSeyQiQOFDg7ONBiSmqRe10wWU',
    appId: '1:655391099057:android:207679935e6ca7d8f73a90',
    messagingSenderId: '655391099057',
    projectId: 'octoloupe-c814f',
    storageBucket: 'octoloupe-c814f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqG3OpEvOwMBVxzTGz9-9aR-6FfGcsXl8',
    appId: '1:655391099057:ios:39a954fb4327b14cf73a90',
    messagingSenderId: '655391099057',
    projectId: 'octoloupe-c814f',
    storageBucket: 'octoloupe-c814f.firebasestorage.app',
    iosBundleId: 'com.example.octoloupe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqG3OpEvOwMBVxzTGz9-9aR-6FfGcsXl8',
    appId: '1:655391099057:ios:39a954fb4327b14cf73a90',
    messagingSenderId: '655391099057',
    projectId: 'octoloupe-c814f',
    storageBucket: 'octoloupe-c814f.firebasestorage.app',
    iosBundleId: 'com.example.octoloupe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1Ku2LIlLT2q5nSt9-49vfPHEV5GraoEo',
    appId: '1:655391099057:web:3df2d2c096fd4694f73a90',
    messagingSenderId: '655391099057',
    projectId: 'octoloupe-c814f',
    authDomain: 'octoloupe-c814f.firebaseapp.com',
    storageBucket: 'octoloupe-c814f.firebasestorage.app',
    measurementId: 'G-X116X344NP',
  );

}